"""add_user_preferences_and_document_content

Revision ID: 83749aab0481
Revises: 165ea69e5ab0
Create Date: 2026-08-18 12:18:16.495258

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '83749aab0481'
down_revision: str | Sequence[str] | None = '165ea69e5ab0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure content column exists (idempotent)
    op.execute("ALTER TABLE documents ADD COLUMN IF NOT EXISTS content TEXT;")

    # Add preferences column to users table (idempotent)
    op.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS preferences JSONB;")
    # Set default value for existing rows
    op.execute("UPDATE users SET preferences = '{}'::jsonb WHERE preferences IS NULL")
    # Make column NOT NULL
    op.alter_column('users', 'preferences', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###
